create database customer_behavior;
use customer_behavior;
select * from customer limit 10;
-- Q)what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as 'revenue' from customer group by gender;

-- Q)Which customer used a discount but still spend more than the average purchase amount?
select customer_id,purchase_amount from customer where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer);

-- Q)Which are top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as 'Average  product Rating' from customer group by item_purchased order by avg(review_rating) desc limit 5;

-- Q)Compare the average purchase amount btw Standard and exprress shipping?
select shipping_type,round(avg(purchase_amount),2) as 'Average Purchase amount' from customer where shipping_type in ('Standard','Express') group by shipping_type;

-- Q)Do subscribed customers spend more? compare average spend and total revenue btw subscribers and non-subscribers?
select subscription_status,count(customer_id) as 'Total Customers',round(avg(purchase_amount),2)  as 'Average Purchase Amount',sum(purchase_amount) as 'Total Revenue' from customer group by subscription_status;

-- Q)which 5 products have the highest percentage of purchases with discount applied?
-- which product rely heavily on discount to sell
select item_purchased,round(sum(case when discount_applied='Yes' then 1 else 0 end)/count(*)*(100),2) as 'discount_rate' from customer
group by item_purchased order by discount_rate desc limit 5; 

-- Q)segment customers into new,returning and loyal based on their total number of previous purchases,and show the count of each segment?
with customer_type as (
select customer_id,previous_purchases,
case 
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returing'
else 'Loyal'
end as customer_segment from customer
)
select customer_segment,count(*) as 'Number of Customers' from customer_type group by customer_segment;

-- Q)What are the top three most purchased product within each category?
  with item_counts as (
  select category,item_purchased,count(customer_id) as 'total_orders',
  row_number() over(partition by category order by count(customer_id) desc) as 'item_rank' from customer
  group by category,item_purchased)
  select item_rank,category,item_purchased,total_orders from item_counts where item_rank<=3;
  
-- WITH item_counts AS (...)
-- This creates a CTE (Common Table Expression).
-- Think of it as creating a temporary result table called item_counts that exists only while this query runs.
-- PARTITION BY → Separate into groups
-- ORDER BY → Decide the ranking order
-- ROW_NUMBER() → Give each row a number
-- WHERE rank <= 3 → Keep the top 3

-- Q)Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as 'repated_buyers' from customer where previous_purchases>5 group by subscription_status;

-- Q)what is the rvrnue contribution of each age group?
select age_group,sum(purchase_amount)as 'Total_revenue' from customer group by age_group order by Total_revenue desc;